FROM alpine:3.12

RUN apk update
RUN apk add nginx
RUN apk add vim

COPY /conf/nginx.conf /etc/nginx



#sudo docker build -t nginx .
#sudo docker run --name nginxx -it nginx

#sudo docker rm nginxx
#sudo docker rmi nginx

#nginx located
